spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/spring_batch
    username: user
    password: 123456
  batch:
    initialize-schema: always

app:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/migracao_dados
    username: user
    password: 123456

logging:
  level:
    org: info